name: thaisila02
description: App to Hero

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.12+2
  chewie: ^0.9.10
  dio: ^3.0.10
  http: ^0.12.2
  googleapis_auth: ^0.2.12
  googleapis: ^0.56.1
  google_sign_in: ^4.5.6
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.4+1
# flutter_facebook_login: ^3.0.0
  flutter_svg: ^0.19.0
  cloud_firestore: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/potaFree/
    - assets/images/
    - assets/images/potoTSL/b/
    - assets/images/potoTSL/c/
    - assets/images/potoTSL/d/
    - assets/images/potoTSL/e/
    - assets/images/potoTSL/f/
    - assets/images/potoTSL/g/
    - assets/images/potoTSL/h/
    - assets/images/potoTSL/i/
    - assets/images/potoTSL/j/
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/hello.PNG
    - assets/images/sana.PNG
    - assets/images/3.JPG
    - assets/images/4.JPG
    - assets/images/5.JPG
    - assets/images/6.JPG
    - assets/images/7.JPG
    - assets/images/8.JPG
    - assets/images/3.JPG
    - assets/images/4.JPG
    - assets/images/5.JPG
    - assets/images/6.JPG
    - assets/images/7.JPG
    - assets/images/8.JPG
    - assets/images/9.JPG
    - assets/images/10.JPG
    - assets/images/11.JPG
    - assets/images/12.JPG
    - assets/images/13.JPG
    - assets/images/14.JPG
    - assets/images/15.JPG
    - assets/images/16.JPG
    - assets/images/17.JPG
    - assets/images/18.JPG
    - assets/images/19.JPG
    - assets/images/20.JPG
    - assets/images/21.JPG
    - assets/images/22.JPG
    - assets/images/23.JPG
    - assets/images/24.JPG
    - assets/images/25.JPG
    - assets/images/26.JPG
    - assets/images/27.JPG
    - assets/images/28.JPG
    - assets/images/29.JPG
    - assets/images/30.JPG
    - assets/images/31.JPG
    - assets/images/32.JPG
    - assets/images/33.JPG
    - assets/images/34.JPG
    - assets/images/35.JPG
    - assets/images/36.JPG
    - assets/images/37.JPG
    - assets/images/38.JPG
    - assets/images/39.JPG
    - assets/images/40.JPG
    - assets/images/01.JPG
    - assets/images/02.JPG
    - assets/images/03.JPG
    - assets/images/04.JPG
    - assets/images/05.JPG
    - assets/images/06.JPG
    - assets/images/07.JPG
    - assets/images/08.JPG
    - assets/images/09.JPG
#    - assets/videos/testt/001.mp4
#    - assets/videos/easy/es1/
#    - assets/videos/easy/es2/
#    - assets/videos/easy/es3/
#    - assets/videos/easy/es4/
#    - assets/videos/medium/me1/
#    - assets/videos/medium/me2/
#    - assets/videos/medium/me3/
#    - assets/videos/difficult/di1/
#    - assets/videos/difficult/di2/
#    - assets/videos/difficult/di3/


 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
